name: C++ CI with Conan and CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Python and Conan
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Conan
      run: |
        python -m pip install --upgrade pip
        pip install conan
        conan profile detect --force

    - name: Create Build Directory
      run: mkdir build

    - name: Run Conan Install
      run: conan install .. --output-folder=. --build=missing
      working-directory: build

    - name: Configure with CMake
      run: cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
      working-directory: build

    - name: Build Project
      run: cmake --build . --config Release
      working-directory: build

    - name: Run Executable
      run: ./Release/my_app || ./my_app
      working-directory: build
